// <auto-generated />
namespace MobileManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class phone_number_changed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(phone_number_changed));
        
        string IMigrationMetadata.Id
        {
            get { return "201709021755508_phone_number_changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
