// <auto-generated />
namespace MobileManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class user_is_optional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_is_optional));
        
        string IMigrationMetadata.Id
        {
            get { return "201709031615019_user_is_optional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
